version: '3.5'

networks:
  main:
    name: MiniTwit

services:
  
  minitwitimage-e:
    image: ${DOCKER_USERNAME}/minitwitimage-e
    container_name: minitwit
    networks:
      - main
    ports:
      - '5000:5000'